chat_backend/urls.py
from django.urls import path
from .views import MessagesView


app_name = 'chat_backend'


urlpatterns = [
    path('', MessagesView.as_view(), name='conv_list'),
    path('chat/<path:path>', MessagesView.as_view(), name='messages_with_path')
]

empowered/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from rest_framework import routers
from django.conf.urls.static import static
from chat_backend.api.views import (ConversationViewSet,
                                    MessageViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('messages/', include('chat_backend.urls', namespace="messages")),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


router = routers.DefaultRouter()

router.register("api/conversations", ConversationViewSet,
                basename='Conversations')
router.register("api/messages", MessageViewSet, basename='Messages')

urlpatterns += router.urls

home/urls.py
from django.urls import path
from . import views


app_name = "home"


urlpatterns = [
    path('', views.LandingView.as_view(), name='home'),
    path('resources/', views.ResourcesView.as_view(), name='resources'),
    path('mentors/', views.MentorsView.as_view(), name='mentors'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('profile/<pk>', views.UserProfileDetailView.as_view(),
         name='profile'),
    path('profile/update/<pk>', views.UserProfileUpdateView.as_view(),
         name='update_profile'),
]

templates/about.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <div id="about">
        <div class="container about-content">
            <div class="row">
                <div class="col-12">
                    <h1 class="text-center fw-bold">About Us..</h1>
                    <p>Here at <em>empowerEd</em> we want to provide you with first class education!
                        We believe that every every child deserves a chance to earn and grow, regardless of their background or circumstances. 
                        That's why we're dedicated to providing quality education to all children, and by creating a supportive and nurturing environment that helps them reach their full potential.</p>
                    <p> We believe education should not be a privilege but a given!.</p>
                    <p> You can browse through the resources available, watch lessons on demand or book a free of charge session with a mentor. Your
                        mentor is here to help you through the journey and they are fully qualified to deal with any questions you may have.
                    </p>
                    <a href="/accounts/signup/" class="btn global-action-btn rounded-pill">create account</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
<p>At EmpowerEd we believe that every every child deserves a chance to earn and grow, regardless of their background or circumstances. 
                        That's why we're dedicated to providing quality education to all children, and by creating a supportive and nurturing environment that helps them reach their full potential.</p>
                    <br>
                    <p> We believe education should not be a privilege but a given!.</p>
                    <p> You can browse through the resources
                     available, watch lessons on demand or book a free of charge session with a mentor. Your
                       mentor is here to help you through the journey and they are fully qualified to deal with any questions you may have. </p>

                    <!-- Mission and Vision -->
<div class="container">
  <div class="row">
    <div class="col-sm-6">
      <div class="card">
        <img src= alt="Children">
        <div class="card-block">
          <h3 class="card-title">Our Mission</h3>
          <p class="card-text">
              <div>
  <h2>Our Mission and Values</h2>
  <p>At EmpowerEd, our mission is to empower all children, regardless of their characteristics, to reach their full potential.  We believe that education is the key to success. Every child has the right to access education, healthcare, and opportunities to succeed in life, regardless of their social or economic background. We work towards bridging this gap by connecting students with mentors and providing access to educational resources. </p>

</p>

  <p>We are committed to the following values:</p>
  <ul>
    <li>Equality
        <br> 
        We believe that every child has the right to be treated fairly and with dignity, regardless of their race, gender, religion, or any other characteristic.</li>
    <li>Empowerment
        <br>
        We believe that children have the capacity to be agents of change in their own lives and communities, and we aim to provide them with the tools and resources they need to achieve their goals.</li>
    <li>Inclusion
        <br>
        We believe that all children have the right to participate fully in society, and we strive to create an inclusive environment where every child can thrive.</li>
    <li>Collaboration
        <br>
        We believe that meaningful change can only be achieved through partnerships and cooperation, and we work with other organizations, governments, and communities to achieve our goals.</li>
    <li>Accountability
        <br>
        We are committed to transparency, ethical practices, and measuring our impact to ensure that we are making a difference in the lives of the children we serve.</li>
  </ul>
</div>

   <p> At empowerEd, we are committed to breaking down barriers to education and providing opportunities for underprivileged children to thrive academically. Join us today and become a part of our community of dedicated mentors and students who are passionate about education. </p>

  </p>
  <a href="/accounts/signup/" class="btn global-action-btn rounded-pill">create account</a>
  </div>
   </div>
   </div>
    </div>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" >
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Favicons -->
    <link rel="icon" type="image/png" href="{% static 'assets/img/favicon.ico' %}">

    <!--Core css-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <!--boxicons css-->
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <!--local css-->
    <link rel="stylesheet" href="{% static 'css/base.css' %}" type="text/css">

    <!--Core js-->
    <script src="{% static 'js/base.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.6.3.min.js"></script>
    <script src="https://kit.fontawesome.com/956458a6ca.js" crossorigin="anonymous"></script>
    <title>EmpowerEd |{% block extra_title %} Providing education for all! {% endblock %}</title>
  </head>
  <body>
    {% include 'navbar.html' %}

    <main id="main" class="container page">
    {% block content %}
    <!-- Content -->
    {% endblock %}
    </main>

    {% include 'footer.html' %}   
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" 
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <!--particles-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/particlesjs/2.2.2/particles.min.js"></script>
  </body>

</html>

templates/footer.html
{% load static %}
<footer class="container footer-links text-center">
    <div class="row">

        <div class="col-4">
            <h5>Social Links</h5>
            <ul class="social-links list-unstyled gap-3">
                <li class="nav-list">
                    <a href="https://www.facebook.com/" class="nav-link" target="_blank" rel="noopener" aria-label="visit our Facebook page(open in a new tab)"><small>Facebook</small></a>
                </li>
                <li class="nav-list">
                    <a href="https://www.Twitter.com/" class="nav-link" target="_blank" rel="noopener" aria-label="visit our Twitter page(open in a new tab)"><small>Twitter</small></a>
                </li>
                <li class="nav-list">
                    <a href="https://www.Youtube.com/" class="nav-link" target="_blank" rel="noopener" aria-label="visit our Youtube page(open in a new tab)"><small>Youtube</small></a>
                </li>
                <li class="nav-list">
                    <a href="https://www.Instagram.com/" class="nav-link" target="_blank" rel="noopener" aria-label="visit our Instagram page(open in a new tab)"><small>Instagram</small></a>
                </li>
            </ul>
        </div>
        <div class="col-4">
            <h5>Helpful Links</h5>
            <ul class="helpful-links list-unstyled gap-3">
                <li class="nav-list">
                    <a href="https://www.curajoy.org" class="nav-link" target="_blank" rel="noopener" aria-label="visit Curajoy page(open in a new tab)"><small>Curajoy</small></a>
                </li>
                <li class="nav-list">
                    <a href="https://www.nhs.uk/conditions/autism" class="nav-link" target="_blank" rel="noopener" aria-label="visit Autism page(open in a new tab)"><small>Autism</small></a>
                </li>
                <li class="nav-list">
                    <a href="https://walk.cafod.org.uk" class="nav-link" target="_blank" rel="noopener" aria-label="visit Cafod page(open in a new tab)"><small>Cafod</small></a>
                </li>
                <li class="nav-list">
                    <a href="https://www.scope.org.uk" class="nav-link" target="_blank" rel="noopener" aria-label="visit Scope page(open in a new tab)"><small>Scope</small></a>
                </li>
            </ul>
        </div>
        <div class="col-4">
            <h5>Internal Links</h5>
            <ul class="internal-links list-unstyled gap-3">
                <li class="nav-list">
                    <a href="{% url 'home:home' %}" class="nav-link" target="_blank" rel="noopener" aria-label="visit our Home page(open in a new tab)"><small>Home</small></a>
                </li>
                <li class="nav-list">
                    <a href="{% url 'home:resources' %}" class="nav-link" target="_blank" rel="noopener" aria-label="visit our Resources page(open in a new tab)"><small>Resources</small></a>
                </li>
                <li class="nav-list">
                    <a href="{% url 'home:mentors' %}" class="nav-link" target="_blank" rel="noopener" aria-label="visit our Mentors page(open in a new tab)"><small>Mentors</small></a>
                </li>
                <li class="nav-list">
                    <a href="{% url 'home:about' %}" class="nav-link" target="_blank" rel="noopener" aria-label="visit our About page(open in a new tab)"><small>About</small></a>
                </li>
            </ul>
        </div>
    </div>
</footer>

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="home">
<!-- Hero -->
<div id="hero">
    <canvas class="background"></canvas>
<!--hero callout-->
<div class="container hero-content">
    <div class="row">
        <div class="col-12">
            <section class="container">
                <h2 class="head-text"><span>Empower</span><br><span>the future</span></h2>
                <a class="btn hero-action-btn rounded-pill mb-3" href="{% url 'home:resources' %}" role="button">Start Now</a>
                <p class="lead">Join us in providing access to education for all!</p>
            </section>
        </div>
    </div>
</div>
</div>

{% endblock %}

templates/mentors.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    <div class="row">
        <div class="col-12 mb-5">
        <h1 class="text-center">Mentors</h1>
        </div>
    </div>

    {% if 'mentor_list' %}
    <div class="col-12">
        <div class="container">
            <div class="row">
                {% for mentor in mentor_list %}
                <div class="col-sm-6 col-md-6 col-lg-4 col-xl-3">
                    <div class="mentor-card my-3 mx-auto">
                        <a href="{% url 'home:profile' mentor.user_id.pk %}">
                            <div class="container mentor-image py-4 px-3">
                                <img src="{{ mentor.userpic }}" alt="mentor image" width="200" height="280">
                            </div>
                        </a>
                        <div class="container mentor-info ms-0 ps-1">
                            <a class="text-decoration-none text-dark fs-5 fw-semibold" href="{% url 'home:profile' mentor.user_id.pk %}">{{ mentor.user_id }}</a>
                            <p>{{ mentor.area_of_expertise }}</p>
                            <a href="{% url 'messages:messages_with_path' 'conv' %}{{user.pk}}_{{mentor.user_id.pk}}?q=conv{{user.pk}}_{{mentor.user_id.pk}}" class="btn global-action-btn rounded-pill">contact mentor</a>                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:1 %}
                    <div class="col-12 d-sm-none">
                        <hr">
                    </div>
                {% endif %}
                {% if forloop.counter|divisibleby:2 %}
                    <div class="col-12 d-none d-sm-block d-md-block d-lg-none">
                        <hr">
                    </div>
                {% endif %}
                {% if forloop.counter|divisibleby:3 %}
                <div class="col-12 d-none d-lg-block d-xl-none">
                    <hr>
                </div>
                {% endif %}
                {% if forloop.counter|divisibleby:4 %}
                    <div class="col-12 d-none d-xl-block">
                        <hr>
                    </div>
                {% endif %}
                {% endfor %}
            </div>
        </div>
        <!-- pagination -->
        {% if page_obj.has_other_pages %}
        <nav>
            <ul class="pagination justify-content-center mt-4 mb-2">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link"
                        href="?page=1{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">First</a>
                </li>
                <li class="page-item">
                    <a class="page-link"
                        href="?page={{ page_obj.previous_page_number }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">
                        Previous
                    </a>
                </li>
                {% endif %}

                {% for page_number in page_obj.paginator.page_range %}
                {% if page_number <= page_obj.number|add:3 and page_number >= page_obj.number|add:-3 %}
                {% if page_obj.number == page_number %}
                <li class="page-item active">
                    <a class="page-link"
                        href="?page={{ page_number }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">{{ page_number }}</a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link"
                        href="?page={{ page_number }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">{{ page_number }}</a>
                </li>
                {% endif %}
                {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link"
                        href="?page={{ page_obj.next_page_number }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">
                        Next
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link"
                        href="?page={{ page_obj.paginator.num_pages }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">
                        Last
                    </a>
                </li>
                {% endif %}
            </ul>
        </nav>
        {% endif %}
    </div>
    {% else %}
        <p>Ooops, nothing here.</p>
    {% endif %}
{% endblock %}

templates/navbar.html
{% load static %}
<header class="top-nav fixed-top">
    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
            <div class="row w-100">
                <div class="col-12 col-lg-3 nav d-flex justify-content-between">
                    <!--logo-->
                    <a class="navbar-brand ms-5" href="{% url 'home:home' %}">EmpowerEd</a>
                    <div class="d-flex gap-3 d-lg-none mobile-nav">
                        <!-- messenger icon -->
                        <a href="{% url 'chat_backend:conv_list' %}" class="nav-link" aria-label="Messages">
                            <i class='bx bx-envelope text-muted position-relative fs-1' id="messages">{% include "unread.html" %}</i>
                        </a>
                            <!--hamburger-->
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                    </div>
                </div>
                
                <div class="col-lg-9">
                    <!-- nav items-->
                    <div class="collapse navbar-collapse" id="navbarText">
                        <div class="row w-100">
                            <div class="col-8 d-flex justify-content-around nav-internal-links">
                                <ul class="navbar-nav">
                                    <li class="nav-item">
                                        <a class="nav-link active" aria-current="page" href="{% url 'home:home' %}" title="">Home</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'home:resources' %}" title="">Resources</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'home:mentors' %}" title="">Mentors</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'home:about' %}" title="">About</a>
                                    </li>
                                    <ul class=" list-unstyled d-block d-lg-none">
                                            {% if user.is_authenticated %}
                                        <li class="nav-item">
                                            <a class="nav-link" href="{% url 'account_logout' %}">Logout</a></li>
                                        {% else %}
                                        <li class="nav-item">
                                            <a class="nav-link" href="{% url 'account_signup' %}">Sign Up</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                                        </li>
                                        {% endif %}
                                    </ul>
                                </ul>
                            </div>
                            <div class="col-4 d-none d-lg-flex justify-content-end">
                                <ul class="navbar-nav gap-2">
                                    <!-- user -->
                                    {% if user.is_authenticated %}
                                        <div class="d-flex gap-2">
                                            <a id="user-name" href="{% url 'home:profile' user.pk %}" class="fw-semibold nav-link"><i class='bx bxs-user-circle'></i>&nbsp;{{ user.first_name }}</a>
                                             <!-- messenger icon -->
                                             <a href="{% url 'chat_backend:conv_list' %}" class="nav-link"
                                                 aria-label="Messages">
                                                 <i class='bx bx-envelope fs-4 text position-relative' id="messages">
                                                     {% include "unread.html" %}
                                                 </i>
                                             </a>
                                        </div>
                                    {% endif %}
                                    {% if user.is_authenticated %}
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'account_logout' %}">Logout</a></li>
                                    {% else %}
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'account_signup' %}">Sign Up</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                                    </li>
                                    {% endif %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
      </nav>
</header>

templates/profile.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="row">
    <div class="col-12 mb-5">
        <h1 class="text-center">User Profile</h1>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="row">
                {% if profile.user_id.role == 'Mentor' %}
                <div class="col-10 col-md-6 mx-auto">
                    <div class="user-profile mb-5">
                        <img src="{{ profile.userpic }}" alt="{{ profile }} profile picture">
                        <div class="container profile d-flex gap-2">
                            <p class="fw-semibold mt-3">{{ profile.user_id }}</p>
                            <!-- update icon -->
                            {% if profile.user_id == request.user %}
                            <a href="{% url 'home:update_profile' profile.user_id.pk %}" class="link-primary mx-2 pen"
                                title="Edit Your Profile">
                                <i class="fa-solid fa-pen-to-square"></i>
                            </a>{% endif %}
                        </div>
                        <a href="{% url 'messages:messages_with_path' 'conv' %}{{user.pk}}_{{profile.user_id.pk}}?q=conv{{user.pk}}_{{profile.user_id.pk}}" class="btn global-action-btn rounded-pill">contact mentor</a>
                    </div>
                    <p><strong>Area of Expertise:</strong> {{ profile.area_of_expertise }}</p>
                    <p><strong>Bio:</strong> {{ profile.bio }}</p>

                </div>
                <div class="col-12 col-md-6">
                    <p class="fs-5">Students</p>
                    {% for relationship in mentor_student %}
                    <ul class="list-unstyled">
                        <li><i class="fa-solid fa-graduation-cap me-2"></i><a class="text-decoration-none children" href="{% url 'home:profile' relationship.student_id.user_id.pk %}">{{ relationship.student_id }}</a></li>
                    </ul>
                    {% endfor %}
                </div>

                {% elif profile.user_id.role == 'Student' %}
                <div class="col-10 col-md-5 mx-auto">
                    <div class="user-profile mb-5">
                        <img src="{{ profile.userpic }}" alt="{{ profile }} profile picture">
                        <div class="container profile d-flex gap-2">
                            <p class="fw-semibold">{{ profile }}</p>
                           {% if profile.user_id == request.user %}
                           <a href="{% url 'home:update_profile' profile.user_id.pk %}" class="link-primary mx-2 pen"
                               title="Edit Your Profile">
                               <i class="fa-solid fa-pen-to-square"></i>
                           </a>{% endif %}
                        </div>
                    </div>
                    {% if student_parent %}
                        <p>Parent: <a class="parent text-decoration-none" href="{% url 'home:profile' student_parent.user_id.pk %}">{{ student_parent }}</a></p>
                    {% endif %}
                    <p>Age: {{ age }}</p>
                    <p>Interests: {{ profile.interests }}</p>

                </div>
                <div class="col-12 col-md-7">
                    <!--other informations-->
                    <div class="container sessions">
                        <p class="fs-5 fw-semibold text-center text-uppercase">Upcoming Sessions</p>
                        <div class="row">
                            {% for lesson in lessons %}
                            <div class="col-12">
                                <div class="container sessions-info my-2 py-2">
                                    <div class="d-flex justify-content-between">
                                        <p><i class="fa-solid fa-wand-magic-sparkles me-2"></i><a class="sessions-mentor" href="{% url 'home:profile' lesson.mentor.user_id.pk %}">{{ lesson.mentor.user_id }}</a></p>
                                        <p class="text-muted">{{ lesson.mentor.area_of_expertise }}</p>
                                    </div>
                                    <div class="d-flex justify-content-between">
                                        <small><i class="fa-solid fa-bolt me-2"></i> {{ lesson.start_time }}</small>
                                        <small><i class="fa-solid fa-star me-2"></i> {{ lesson.end_time }}</small>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>

                {% else %}
                <div class="col-12 col-md-5">
                    <div class="user-profile mb-5">
                        <img src="{{ profile.userpic }}" alt=" {{ profile }}profile picture">
                        <div class="container profile d-flex gap-2">
                            <p class="fw-semibold">{{ profile }}</p>
                           {% if profile.user_id == request.user %}
                           <a href="{% url 'home:profile' profile.user_id.pk %}" class="link-primary mx-2 pen"
                               title="Edit Your Profile">
                               <i class="fa-solid fa-pen-to-square"></i>
                           </a>{% endif %}
                        </div>
                        <a href="{% url 'messages:messages_with_path' 'conv' %}{{user.pk}}_{{profile.user_id.pk}}?q=conv{{user.pk}}_{{profile.user_id.pk}}" class="btn global-action-btn rounded-pill">contact parent</a>
                    </div>
                    <p class="fs-5">Children</p>
                    {% for relationship in parent_student %}
                    <ul class="list-unstyled">
                        <li><i class="fa-solid fa-graduation-cap me-2"></i><a class="text-decoration-none children" href="{% url 'home:profile' relationship.user_id.pk %}">{{ relationship }}</a></li>
                    </ul>
                    {% endfor %}
                    
                </div>
                <div class="col-12 col-md-7">
                    <!--other informations-->
                    
                    <div class="container sessions">
                        <p class="fs-5 fw-semibold text-center text-uppercase">Upcoming Sessions</p>
                        {% if lessons is not none %}
                        <div class="row">
                            {% for lesson in lessons %}
                            <div class="col-12">
                                <div class="container sessions-info my-2 py-2">
                                    <p><i class="fa-solid fa-graduation-cap me-2"></i><a class="sessions-student" href="{% url 'home:profile' lesson.student.user_id.pk %}">{{ lesson.student }}</a></p>
                                    <div class="d-flex justify-content-between">
                                        <p><i class="fa-solid fa-wand-magic-sparkles me-2"></i><a class="sessions-mentor" href="{% url 'home:profile' lesson.mentor.user_id.pk %}">{{ lesson.mentor.user_id }}</a></p>
                                        <p class="text-muted">{{ lesson.mentor.area_of_expertise }}</p>
                                    </div>
                                    <div class="d-flex justify-content-between">
                                        <small><i class="fa-solid fa-bolt me-2"></i> {{ lesson.start_time }}</small>
                                        <small><i class="fa-solid fa-star me-2"></i> {{ lesson.end_time }}</small>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                        {% endif %}
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/update_profile.html
{% extends "base.html" %}
{% load static %}

{% load crispy_forms_tags %}
{% block content %}
<div class="row mx-1">
    <div class="container col-lg-8 mt-1">
        <div class="d-flex justify-content-between">
            <h2 class="mb-3">Edit Profile</h2>
            <a class="fs-5 text-empower text-decoration-none" href="{% url 'home:profile' user.pk %}">{{ request.user }}</a>
        </div>
        <form class="login" method="POST" action="{% url 'account_login' %}">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="mb-3">
                <button class="btn global-action-btn rounded-pill" type="submit">Save</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}